### ISSUE TITLE
Launcher crashes on opening app list (swiping up)

### ISSUE THREAD

**Issue by M1cR0xf7** [tanujnotes/Olauncher#282]
Version: v3.6.5

android 13

It was working on the previous version.

**Comment by langfingaz** [comment]
I am also experiencing this since the last update vai f-droid store. Sometimes when swiping up, other times after swiping up and starting to type.

**Comment by langfingaz** [comment]
I found a way to always reproduce this error: Swipe up to open the app list and scroll all the way down. When one reaches the end, the app crashes.

Here is the log captured with `adb logcat`. Not sure if I can provide other log that might be helpful.

After the crash I get a bottom-popup "Select a home app" where I can select to start the Olauncher "just once" or "always".

```
01-19 09:43:01.021 29160 29160 D AndroidRuntime: Shutting down VM
01-19 09:43:01.023 29160 29160 E AndroidRuntime: FATAL EXCEPTION: main
01-19 09:43:01.023 29160 29160 E AndroidRuntime: Process: app.olauncher, PID: 29160
01-19 09:43:01.023 29160 29160 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	... 1 more
01-19 09:43:01.023 29160 29160 E AndroidRuntime: Caused by: android.content.pm.PackageManager$NameNotFoundException: com.whatsapp
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:516)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:499)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:493)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.activity.h.K(Unknown Source:18)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at t1.b.b(SourceFile:105)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$s.i(SourceFile:1031)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$c.b(SourceFile:59)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.J0(SourceFile:1)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.y0(SourceFile:54)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.O0(Unknown Source:34)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.i0(Unknown Source:6)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.T(SourceFile:42)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$y.run(SourceFile:109)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
01-19 09:43:01.023 29160 29160 E AndroidRuntime: 	... 3 more
01-19 09:43:01.027  1528 29209 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-19 09:43:01.028  1528  7414 W ActivityTaskManager:   Not force finishing home activity app.olauncher/.MainActivity
01-19 09:43:01.028  1528  7414 W ActivityTaskManager:   Not force finishing home activity app.olauncher/.MainActivity
01-19 09:43:01.028  1528  7414 I ActivityTaskManager: Clearing package preferred activities from app.olauncher
01-19 09:43:01.030 29160 29160 I Process : Sending signal. PID: 29160 SIG: 9
01-19 09:43:01.056  1528  2486 I WindowManager: WIN DEATH: Window{c1d26a3 u0 app.olauncher/app.olauncher.MainActivity}
01-19 09:43:01.056  1528  2486 W InputManager-JNI: Input channel object 'c1d26a3 app.olauncher/app.olauncher.MainActivity (client)' was disposed without first being removed with the input manager!
01-19 09:43:01.057   897   897 I Zygote  : Process 29160 exited due to signal 9 (Killed)
01-19 09:43:01.057  1528  7414 I ActivityManager: Process app.olauncher (pid 29160) has died: fg  TOP 
01-19 09:43:01.058  1528  1563 I libprocessgroup: Successfully killed process cgroup uid 10208 pid 29160 in 0ms
01-19 09:43:01.063  1528  7414 W ActivityTaskManager: Force removing ActivityRecord{8276417 u0 app.olauncher/.MainActivity} t457}: app died, no saved state
01-19 09:43:01.064  1528  7414 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=android/com.android.internal.app.ResolverActivity (has extras)} from uid 0
01-19 09:43:01.070  1528  7414 V SplashScreenExceptionList: SplashScreen checking exception for package android (target sdk:33) -> false
01-19 09:43:01.070  1528  7414 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (61501646)
01-19 09:43:01.075  1528  1565 W libprocessgroup: Failed to open /dev/blkio//cgroup.procs: No such file or directory
01-19 09:43:01.076  1528  2486 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10104/... pkg=com.google.android.googlequicksearchbox } U=0: not found
01-19 09:43:01.077  1528  1553 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
01-19 09:43:01.085   741   741 E ClientCache: failed to get buffer, invalid process token
01-19 09:43:01.089  2712  4002 E OpenGLRenderer: Unable to match the desired swap behavior.
01-19 09:43:01.105     0     0 I [20230119_09:43:01.105218]@0 BQ: fg_soc_calibrate: soc:100, soc_calib:94, VOLT:4366, current:-315
01-19 09:43:01.146 27661 29041 D AbstractResolverComp: Setting watchdog timer for 500ms
01-19 09:43:01.146 27661 27661 D ResolverActivity: No targets in the current profile
01-19 09:43:01.163  1528  7414 D CoreBackPreview: Window{6d79bdd u0 android/com.android.internal.app.ResolverActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@1e7f623, mPriority=0}
01-19 09:43:01.169 27661 27661 D ResolverActivity: No targets in the current profile
01-19 09:43:01.176 27661 27661 D ResolverActivity: No targets in the current profile
01-19 09:43:01.187 27661 27661 D AbstractResolverComp: RANKER_SERVICE_RESULT
01-19 09:43:01.188  1528  1554 W WindowManager: Failed to deliver inset state change to w=Window{c1d26a3 u0 app.olauncher/app.olauncher.MainActivity EXITING}
01-19 09:43:01.188  1528  1554 W WindowManager: android.os.DeadObjectException
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4013)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4$com-android-server-wm-InsetsStateController(InsetsStateController.java:351)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(Unknown Source:2)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.wm.WindowAnimator.lambda$new$1$com-android-server-wm-WindowAnimator(WindowAnimator.java:106)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(Unknown Source:2)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-19 09:43:01.188  1528  1554 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
01-19 09:43:01.193  1528  1550 W ziparchive: Unable to open '/system/framework/framework-res.dm': No such file or directory
01-19 09:43:01.193  1528  1550 W ziparchive: Unable to open '/system/framework/framework-res.dm': No such file or directory
01-19 09:43:01.194  1528  1550 I ActivityTaskManager: Displayed android/com.android.internal.app.ResolverActivity: +128ms
01-19 09:43:01.201 27661 27661 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{app.olauncher/app.olauncher.MainActivity}, intent component: ComponentInfo{app.olauncher/app.olauncher.MainActivity}
01-19 09:43:01.202 27661 27661 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}, intent component: ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}
01-19 09:43:01.223  1528  1554 W WindowManager: Failed to deliver inset state change to w=Window{c1d26a3 u0 app.olauncher/app.olauncher.MainActivity EXITING}
01-19 09:43:01.223  1528  1554 W WindowManager: android.os.DeadObjectException
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4013)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4$com-android-server-wm-InsetsStateController(InsetsStateController.java:351)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(Unknown Source:2)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:835)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:779)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-19 09:43:01.223  1528  1554 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
01-19 09:43:01.271  1528  1553 W ActivityManager: setHasOverlayUi called on unknown pid: 29160
01-19 09:43:01.286   741   773 W TransactionTracing: Could not find layer handle 0x7018aa33f0
01-19 09:43:01.286   741   773 W TransactionTracing: Could not find layer handle 0x7018a9ff10
01-19 09:43:01.286   741   773 W TransactionTracing: Could not find layer handle 0x7018aa0ab0
01-19 09:43:01.286   741   773 W TransactionTracing: Could not find layer handle 0x7018aa0ab0
01-19 09:43:01.286   741   773 W TransactionTracing: Could not find layer handle 0x7018a9ff10
01-19 09:43:01.288   741   741 E BpTransactionCompletedListener: Failed to transact (-32)
01-19 09:43:01.428     0     0 E [20230119_09:43:01.428543]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:01.454   741   773 W TransactionTracing: Could not find layer handle 0x7018aa22b0
01-19 09:43:01.454   741   773 W TransactionTracing: Could not find layer handle 0x7018a84850
01-19 09:43:01.454   741   773 W TransactionTracing: Could not find layer handle 0x7018a84850
01-19 09:43:01.455   741   773 W TransactionTracing: Could not find layer handle 0x7018aa22b0
01-19 09:43:01.460     0     0 E [20230119_09:43:01.460293]@2 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:01.465     0     0 W [20230119_09:43:01.464938]@2 healthd: battery l=94 v=4366 t=19.6 h=2 st=2 c=315000 fc=2878000 cc=0 chg=u
01-19 09:43:01.470     0     0 E [20230119_09:43:01.469921]@2 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:01.489  2497  3765 D PowerUI : can't show warning due to - plugged: true status unknown: false
01-19 09:43:01.743     0     0 E [20230119_09:43:01.742366]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:01.756     0     0 E [20230119_09:43:01.752970]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:01.761     0     0 W [20230119_09:43:01.761280]@0 healthd: battery l=94 v=4366 t=19.6 h=2 st=2 c=315000 fc=2878000 cc=0 chg=u
01-19 09:43:01.770     0     0 E [20230119_09:43:01.767007]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:02.304     0     0 E [20230119_09:43:02.303386]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:02.331     0     0 E [20230119_09:43:02.328821]@3 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:02.335     0     0 W [20230119_09:43:02.334352]@3 healthd: battery l=94 v=4304 t=19.6 h=2 st=2 c=296000 fc=2878000 cc=0 chg=u
01-19 09:43:02.340     0     0 E [20230119_09:43:02.340294]@3 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:02.366  2497  3779 D PowerUI : can't show warning due to - plugged: true status unknown: false
01-19 09:43:02.374  1528  1568 E system_server: Cannot read thread CPU times for PID 1528
01-19 09:43:02.604     0     0 E [20230119_09:43:02.601491]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:02.611     0     0 E [20230119_09:43:02.609576]@3 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:02.617     0     0 W [20230119_09:43:02.616638]@1 healthd: battery l=94 v=4304 t=19.6 h=2 st=2 c=296000 fc=2878000 cc=0 chg=u
01-19 09:43:02.625     0     0 E [20230119_09:43:02.623876]@1 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:03.486     0     0 E [20230119_09:43:03.484524]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:03.506     0     0 E [20230119_09:43:03.506377]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:03.513     0     0 W [20230119_09:43:03.513206]@1 healthd: battery l=94 v=4366 t=19.6 h=2 st=2 c=352000 fc=2878000 cc=0 chg=u
01-19 09:43:03.520     0     0 E [20230119_09:43:03.519694]@1 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:03.541  2497  3146 D PowerUI : can't show warning due to - plugged: true status unknown: false
01-19 09:43:04.095     0     0 E [20230119_09:43:04.094767]@0 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:04.104     0     0 E [20230119_09:43:04.102713]@1 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:04.114     0     0 W [20230119_09:43:04.108205]@1 healthd: battery l=94 v=4366 t=19.6 h=2 st=2 c=352000 fc=2878000 cc=0 chg=u
01-19 09:43:04.114     0     0 E [20230119_09:43:04.113629]@1 FG: fg_psy_get_property: unsupported property 76
01-19 09:43:04.140  2497  3809 D PowerUI : can't show warning due to - plugged: true status unknown: false
```

**Comment by tanujnotes** [comment]
Please try the latest version and update here if possible.

**Comment by langfingaz** [comment]
Thanks for the update. The app does no longer crash when scrolling all the way down. And I didn't manage to get it crash (occasionally) by swiping up and starting to type.

So this issue seems resolved for me :)

**Comment by M1cR0xf7** [comment]
Latest version solved the problem
