### ISSUE TITLE
Crash when renaming app

### ISSUE THREAD

**Issue by BWPanda** [tanujnotes/Olauncher#373]
I was trying to rename an app, and Olauncher kept crashing:

```
type: crash
osVersion: google/bramble/bramble:13/TQ3A.230705.001/2023070500:user/release-keys
package: app.olauncher:66
process: app.olauncher
processUptime: 205985 + 257 ms

java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
	at android.widget.TextView.onKeyUp(TextView.java:8948)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2925)
	at android.view.View.dispatchKeyEvent(View.java:14988)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1902)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4267)
	at w.h.d(Unknown Source:0)
	at h0.f.b(SourceFile:11)
	at w.h.dispatchKeyEvent(Unknown Source:18)
	at androidx.appcompat.app.c.dispatchKeyEvent(SourceFile:13)
	at h.h.dispatchKeyEvent(Unknown Source:2)
	at d.g$h.dispatchKeyEvent(Unknown Source:19)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:402)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6704)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6570)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6030)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6218)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6275)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9202)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9153)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9122)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:5795)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5678)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

**Comment by tanujnotes** [comment]
Does this happen with a particular app or any app you try to rename? Also, if you phone language is anything other than English, let me know.

**Comment by BWPanda** [comment]
I was trying to rename a particular app (Aegis) to 'Authenticator'. Phone is English.

However I just tried again (renaming Aegis to 'Test' then 'Authenticator') and it worked fine. Then renamed a bunch of other apps and that worked fine too.

So I can't reproduce this anymore, and it appears to be working now. So I'll close this issue. Sorry.
