### ISSUE TITLE
show hidden app crash

### ISSUE THREAD

**Issue by agiardina** [tanujnotes/Olauncher#459]
When I try to show an hidden application, the launcher crash

type: crash
osVersion: Fairphone/FP4eea/FP4:13/TQ3A.230901.001/eng.emy.20240211.055721:user/release-keys
package: app.olauncher:76
process: app.olauncher

java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:167)
	at i2.l.c(SourceFile:25)
	at i2.e.onClick(SourceFile:108)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

**Comment by tanujnotes** [comment]
Please reinstall the app.

**Comment by agiardina** [comment]
Reinstalling fixed it
