### ISSUE TITLE
FATAL EXCEPTION: wmshell.splashscreen

### ISSUE THREAD

**Issue by InvisOn** [tanujnotes/Olauncher#553]
I noticed that sometimes "System UI" crashes.

I don't know of it has something to do with Olauncher.

Below is `adb logcat --buffer=crash` output:
```
12-08 13:36:09.049  3227  3242 E AndroidRuntime: FATAL EXCEPTION: wmshell.splashscreen
12-08 13:36:09.049  3227  3242 E AndroidRuntime: Process: com.android.systemui, PID: 3227
12-08 13:36:09.049  3227  3242 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2995)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2978)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2920)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.app.IActivityTaskManager$Stub$Proxy.onSplashScreenViewCopyFinished(IActivityTaskManager.java:3695)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.app.ActivityTaskManager.onSplashScreenViewCopyFinished(ActivityTaskManager.java:218)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at com.android.wm.shell.startingsurface.StartingSurfaceDrawer.copySplashScreenView(StartingSurfaceDrawer.java:550)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at com.android.wm.shell.startingsurface.StartingWindowController.lambda$copySplashScreenView$1(StartingWindowController.java:164)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at com.android.wm.shell.startingsurface.StartingWindowController.$r8$lambda$Nsve7j-qdEujmRJ49hHw0qVTWtY(Unknown Source:0)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at com.android.wm.shell.startingsurface.StartingWindowController$$ExternalSyntheticLambda6.run(Unknown Source:4)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
12-08 13:36:09.049  3227  3242 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.view.SurfaceControl.-$$Nest$mcheckNotReleased(Unknown Source:0)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.view.SurfaceControl$Transaction.checkPreconditions(SurfaceControl.java:2816)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at android.view.SurfaceControl$Transaction.setPosition(SurfaceControl.java:2984)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at com.android.server.wm.TaskOrganizerController.applyStartingWindowAnimation(TaskOrganizerController.java:489)
12-08 13:36:09.049  3227  3242 E AndroidRuntime:        at com.android.server.wm.ActivityRecord.onCopySplashScreenFinish(ActivityRecord.java:2635)
```

**Comment by tanujnotes** [comment]
Try restarting the device.
